### ISSUE TITLE
[Question] Use of the created network in a Master's Thesis?

### ISSUE THREAD

**Issue by Fooughhy** [martinjm97/ENNUI#124]
Hello!

We are in the process of writing our Master's Thesis and would like use this tool to visualize a network we are using. What we would like to do is to simply screenshot the created network and include it in our thesis while explaining the concept of neural networks.
Being unfamiliar with licenses, we would simply like to ask if this is possible with the MIT license you are using for this repo?

**Comment by martinjm97** [comment]
Hi @Fooughhy,

Yup, no license issues here. Suggestion: maybe try editing the HTML with inspect element and change the background to be white. Feel free to cite the repo or the website. Maybe some of the explanations in the education tab will be of some use. I'm delighted to hear you're using Ennui and good luck with your thesis! I'd enjoy seeing the final product.
