### ISSUE TITLE
Keep Saying "Loading MNIST dataset"

### ISSUE THREAD

**Issue by XuShenLZ** [martinjm97/ENNUI#130]
When I enter the webpage: https://math.mit.edu/ennui/, the message "Loading MNIST dataset" keeps being on the top, and nothing changes for a long time. Is there anything wrong with the system?

**Comment by sgrosser** [comment]
Yes are in the middle of fixing this. It is a problem with the hosting.

**Comment by XuShenLZ** [comment]
Thanks for the quick reply! Please let me know when it is fixed

**Comment by sgrosser** [comment]
Should be all fixed now! Let me know and I'll close this issue.

**Comment by XuShenLZ** [comment]
How long it is supposed to take? Unfortunately, it is still there when I open the webpage, for about 2mins already

**Comment by XuShenLZ** [comment]
Oh it works now!

**Comment by sgrosser** [comment]
Great! Closing this issue. Let us know what you end up using this for! We always love to see people using Ennui 😃
